from pathlib import Path
import os

from dotenv import load_dotenv


PROJECT_ROOT = Path(__file__).resolve().parent.parent
load_dotenv(PROJECT_ROOT / ".env")

NOTES_DIR = PROJECT_ROOT / "notes"
VECTOR_STORE_DIR = PROJECT_ROOT / "vectorstore"
VECTORE_DB_FILE = VECTOR_STORE_DIR / "chroma.sqlite3"
VECTOR_STORE_STATE_FILE = VECTOR_STORE_DIR / "build_state.txt"

# 自动创建
for dir in (NOTES_DIR, VECTOR_STORE_DIR):
    dir.mkdir(exist_ok=True)


MOONSHOT_API_KEY = os.getenv("MOONSHOT_API_KEY")
MOONSHOT_BASE_URL = os.getenv("MOONSHOT_BASE_URL")
MOONSHOT_MODEL = os.getenv("MOONSHOT_MODEL")
MOONSHOT_TEMPERATURE = os.getenv("MOONSHOT_TEMPERATURE")
MOONSHOT_MAX_TOKENS = os.getenv("MOONSHOT_MAX_TOKENS")
MOONSHOT_TOP_P = os.getenv("MOONSHOT_TOP_P")
MOONSHOT_FREQUENCY_PENALTY = os.getenv("MOONSHOT_FREQUENCY_PENALTY")
MOONSHOT_PRESENCE_PENALTY = os.getenv("MOONSHOT_PRESENCE_PENALTY")

SILICONFLOW_API_KEY = os.getenv("SILICONFLOW_API_KEY")
SILICONFLOW_BASE_URL = os.getenv("SILICONFLOW_BASE_URL")
SILICONFLOW_MODEL = os.getenv("SILICONFLOW_MODEL")

SILICONFLOW_PRESENCE_PENALTY = os.getenv("SILICONFLOW_PRESENCE_PENALTY")


LANGSMITH_TRACING = os.getenv("LANGSMITH_TRACING")
LANGSMITH_API_KEY = os.getenv("LANGSMITH_API_KEY")
LANGSMITH_PROJECT = os.getenv("LANGSMITH_PROJECT")

TEMPERATURE = 0.1
CHUNK_SIZE = 500
CHUNK_OVERLAP = 50
RETEIEVER_K = 3
VECTOR_STORE_COLLECTION_NAME = "note_assistant"
DEFAULT_THREAD_ID = "note_assistant"
